# Generated by Django 5.1.7 on 2025-03-18 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('dimming_protocol', models.CharField(choices=[('ELV', 'ELV'), ('Triac', 'Triac'), ('0-10V', '0-10V')], max_length=100)),
                ('manufacturer_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Luminaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=255)),
                ('dimming_protocol', models.CharField(choices=[('ELV', 'ELV'), ('Triac', 'Triac'), ('0-10V', '0-10V')], max_length=100)),
                ('manufacturer_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimmerCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_luminaires', models.IntegerField()),
                ('max_luminaires', models.IntegerField()),
                ('min_dimming_percentage', models.FloatField()),
                ('max_dimming_percentage', models.FloatField()),
                ('low_end_start_time', models.FloatField()),
                ('visual_test', models.BooleanField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('dimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dimmer_matching.dimmer')),
                ('luminaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dimmer_matching.luminaire')),
            ],
        ),
    ]
