# Generated by Django 5.1.7 on 2025-03-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimmer_matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luminaire',
            name='max_power',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='luminaire',
            name='status',
            field=models.CharField(choices=[('Not Tested', 'Not Tested'), ('Tested', 'Tested')], default='Not Tested', max_length=20),
        ),
    ]
