# Generated by Django 5.1.7 on 2025-03-18 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimmer_matching', '0002_luminaire_max_power_luminaire_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimmer',
            name='dimnumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimmer',
            name='luminaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dimmer_matching.luminaire'),
            preserve_default=False,
        ),
    ]
