# Generated by Django 5.1.7 on 2025-03-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimmer_matching', '0003_dimmer_dimnumber_dimmer_luminaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimmer',
            name='dimnumber',
        ),
        migrations.RemoveField(
            model_name='dimmer',
            name='luminaire',
        ),
        migrations.AddField(
            model_name='dimmer',
            name='dim_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimmer',
            name='max_power',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
